baseURL: 'http://hypsen.org/'
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
title: HypSen
theme: hello-friend-ng
paginate: 100

enableRobotsTXT: true

params:
  author:
    name: ML
  dateform: 'Jan 2, 2006'
  dateformShort: Jan 2
  dateformNum: '2006-01-02'
  dateformNumTime: '2006-01-02 15:04'
  enableThemeToggle: true
  enableSharingButtons: true
  homeSubtitle: <div>This site covers hyper-sensitivity to light. <br/> <a href="/en/home">Browse in English</a></div>&#x2022;<div>Ce site traite de l'hyper-sensibilité à la lumière.<br/><a href="/fr/accueil">Naviguer en Français</a></div>
  footer:
    trademark: true
    rss: true
    copyright: false
    author: true
    bottomText:
      - 'Theme by <a href="https://github.com/rhazdon">D. Atlialp</a>'
  logo:
    logoMark: ' '
    logoCursorDisabled: true

taxonomies:
  category: blog
  tag: tags
  series: series

languages:
  fr:
    languageName: Français
    params:
      title: HypSen
      keywords: 'hyper-sensibilité à la lumière'
      copyright: >-
        <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank"
        rel="noopener">CC BY-NC 4.0</a>
      readOtherPosts: Voir les autres pages.
      logo:
        logoMark: ' '
        logoCursorDisabled: true
        logoHomeLink: /fr/accueil
        logoText: 'Accueil'
      footer:
        trademark: true
        rss: true
        copyright: false
        author: true
        bottomText:
          - 'Thème inspiré de <a href="https://github.com/rhazdon">DA</a>'
    menu:
      main:
        - url: fr/adaptation
          name: Adaptations
          weight: 10
        - url: fr/a-propos
          name: À propos
          weight: 20
        - url: ../en/home
          name: EN
          weight: 1000
  en:
    languageName: English
    params:
      title: HypSen
      keywords: 'hyper-sensitivity to light'
      copyright: >-
        <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank"
        rel="noopener">CC BY-NC 4.0</a>
      readOtherPosts: Read other posts
      logo:
        logoMark: ' '
        logoCursorDisabled: true
        logoHomeLink: /en/home
        logoText: 'Home'
      footer:
        trademark: true
        rss: true
        copyright: false
        author: true
        bottomText:
          - 'Theme adapted from <a href="https://github.com/rhazdon">DA</a>'
    menu:
      main:
        - url: en/adaptation
          name: Adaptations
          weight: 10
        - url: en/about
          name: About
          weight: 20
        - url: ../fr/accueil
          name: FR
          weight: 1000
